// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVF9goSMHIUkmzT_jMsHWQR5vI-XnqidQ',
    appId: '1:197608348331:web:b193e17cbe7161679fb5ee',
    messagingSenderId: '197608348331',
    projectId: 'spotify-29efb',
    authDomain: 'spotify-29efb.firebaseapp.com',
    storageBucket: 'spotify-29efb.firebasestorage.app',
    measurementId: 'G-Y97XRMZXDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJa3p6XkAlkHsMJuati-FZRLuzTyRcsxA',
    appId: '1:197608348331:android:f97d06bca7a29cb19fb5ee',
    messagingSenderId: '197608348331',
    projectId: 'spotify-29efb',
    storageBucket: 'spotify-29efb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACgE0RU9eFhWWHUm7K_fXkl7669G18_HI',
    appId: '1:197608348331:ios:515516b2ec7b04449fb5ee',
    messagingSenderId: '197608348331',
    projectId: 'spotify-29efb',
    storageBucket: 'spotify-29efb.firebasestorage.app',
    iosBundleId: 'com.example.sptiyGrand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACgE0RU9eFhWWHUm7K_fXkl7669G18_HI',
    appId: '1:197608348331:ios:515516b2ec7b04449fb5ee',
    messagingSenderId: '197608348331',
    projectId: 'spotify-29efb',
    storageBucket: 'spotify-29efb.firebasestorage.app',
    iosBundleId: 'com.example.sptiyGrand',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVF9goSMHIUkmzT_jMsHWQR5vI-XnqidQ',
    appId: '1:197608348331:web:0b4e42c84fc76ea09fb5ee',
    messagingSenderId: '197608348331',
    projectId: 'spotify-29efb',
    authDomain: 'spotify-29efb.firebaseapp.com',
    storageBucket: 'spotify-29efb.firebasestorage.app',
    measurementId: 'G-3457TT257R',
  );
}
